use OSI_Student12_DB

select FINL_EMPLOYEE.EMPLOYEE_ID,
		EMPLOY_FIRST_NAME,
		EMPLOY_LAST_NAME,
		EMPLOY_PHONE_NUM,
		SHIFT_NUM
from FINL_EMPLOYEE
join FINL_TIME_TABLE
	on FINL_EMPLOYEE.EMPLOYEE_ID = FINL_TIME_TABLE.EMPLOYEE_ID;