create trigger t_new_sched_shift
	on FINL_SCHEDULED_SHIFT
after insert
as
update FINL_SCHEDULED_SHIFT
set SCHED_TIME_TOTAL = ABS(DATEDIFF(HOUR,INSERTED.SCHED_TIME_START, INSERTED.SCHED_TIME_END)) from inserted
where FINL_SCHEDULED_SHIFT.SHIFT_NUM = INSERTED.SHIFT_NUM;